// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForZig() {
  return window['go']['main']['App']['BrowseForZig']();
}

export function CreateDir(arg1) {
  return window['go']['main']['App']['CreateDir'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function DeletePath(arg1) {
  return window['go']['main']['App']['DeletePath'](arg1);
}

export function GetBuildSteps() {
  return window['go']['main']['App']['GetBuildSteps']();
}

export function GetFileTree(arg1) {
  return window['go']['main']['App']['GetFileTree'](arg1);
}

export function GetGitStatus() {
  return window['go']['main']['App']['GetGitStatus']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetProjectRoot() {
  return window['go']['main']['App']['GetProjectRoot']();
}

export function GetZigInfo() {
  return window['go']['main']['App']['GetZigInfo']();
}

export function GetZigPath() {
  return window['go']['main']['App']['GetZigPath']();
}

export function KillProc() {
  return window['go']['main']['App']['KillProc']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RenamePath(arg1, arg2) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2);
}

export function RetryZigDetection() {
  return window['go']['main']['App']['RetryZigDetection']();
}

export function RunZig(arg1) {
  return window['go']['main']['App']['RunZig'](arg1);
}

export function SaveAs(arg1, arg2) {
  return window['go']['main']['App']['SaveAs'](arg1, arg2);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function ScaffoldProject(arg1, arg2) {
  return window['go']['main']['App']['ScaffoldProject'](arg1, arg2);
}

export function SendInput(arg1) {
  return window['go']['main']['App']['SendInput'](arg1);
}

export function SetZigPath(arg1) {
  return window['go']['main']['App']['SetZigPath'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function ZigCheck(arg1) {
  return window['go']['main']['App']['ZigCheck'](arg1);
}

export function ZigFmt(arg1) {
  return window['go']['main']['App']['ZigFmt'](arg1);
}

export function ZigVersion() {
  return window['go']['main']['App']['ZigVersion']();
}
