// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BrowseForZig():Promise<string>;

export function CreateDir(arg1:string):Promise<string>;

export function CreateFile(arg1:string):Promise<string>;

export function DeletePath(arg1:string):Promise<string>;

export function GetBuildSteps():Promise<Array<main.BuildStep>>;

export function GetFileTree(arg1:string):Promise<main.FileNode>;

export function GetGitStatus():Promise<main.GitStatus>;

export function GetPlatform():Promise<string>;

export function GetProjectRoot():Promise<string>;

export function GetZigInfo():Promise<Record<string, string>>;

export function GetZigPath():Promise<string>;

export function KillProc():Promise<void>;

export function OpenFile():Promise<Record<string, string>>;

export function OpenFolder():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RenamePath(arg1:string,arg2:string):Promise<string>;

export function RetryZigDetection():Promise<Record<string, string>>;

export function RunZig(arg1:string):Promise<void>;

export function SaveAs(arg1:string,arg2:string):Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function ScaffoldProject(arg1:string,arg2:string):Promise<string>;

export function SendInput(arg1:string):Promise<void>;

export function SetZigPath(arg1:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<string>;

export function ZigCheck(arg1:string):Promise<Array<main.Diag>>;

export function ZigFmt(arg1:string):Promise<string>;

export function ZigVersion():Promise<string>;
